# Generated by Django 5.0.4 on 2024-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join_Journey',
            new_name='JoinJourney',
        ),
    ]
