# Generated by Django 5.0.4 on 2024-05-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_commentimagejourney_imagejourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejourney',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
