# Generated by Django 5.0.4 on 2024-05-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_tag_journey_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinjourney',
            name='content',
        ),
    ]
