# Generated by Django 5.0.4 on 2024-05-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_imagejourney_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimagejourney',
            name='imagejourney',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journeys.imagejourney'),
        ),
    ]
