# Generated by Django 5.0.4 on 2024-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_commentimagejourney_imagejourney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevisit',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='place_images/%Y/%m'),
        ),
    ]
