# Generated by Django 5.0.4 on 2024-05-17 17:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_alter_journey_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='main_image'),
        ),
    ]
