# Generated by Django 5.0.4 on 2024-05-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_alter_placevisit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='active',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
