# Generated by Django 5.0.4 on 2024-06-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0010_journey_end_date_journey_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='comments_closed',
            field=models.BooleanField(default=False),
        ),
    ]
