# Generated by Django 5.0.4 on 2024-06-12 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0011_journey_comments_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevisit',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placevisits', to='journeys.journey'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
