# Generated by Django 5.0.4 on 2024-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0012_alter_placevisit_journey_alter_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
