# Generated by Django 5.0.4 on 2024-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0013_journey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
