# Generated by Django 5.0.4 on 2024-05-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanhtrinh', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
